=== BENJAMINDTS/FPSuperiorDAW/xml/UD.04/TiendaDeRopa/TiendaDeRopa.dtd
<!ELEMENT tienda (articulo+)>
<!ELEMENT articulo (nombre, talla, precio)>
<!ATTLIST articulo
          codigo CDATA #REQUIRED
          categoria CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT talla (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio
          moneda CDATA #REQUIRED>

=== BENJAMINDTS/FPSuperiorDAW/1ºDAW/xml/UD.04/TiendaDeRopa/TiendaDeRopa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "TiendaDeRopa.dtd">
<tienda>
    <articulo codigo="001" categoria="ropa">
        <nombre>Camiseta</nombre>
        <talla>M</talla>
        <precio moneda="USD">19.99</precio>
    </articulo>
    <articulo codigo="002" categoria="ropa">
        <nombre>PantalÃ³n</nombre>
        <talla>L</talla>
        <precio moneda="USD">29.99</precio>
    </articulo>
</tienda>
