=== BENJAMINDTS/FPSuperiorDAW/1ºDAW/xml/UD.04/Universidad/universidad.dtd
<!ELEMENT university (department+)>
<!ELEMENT department (name, faculty, courses)>
<!ATTLIST department id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT faculty (professor+)>
<!ELEMENT professor (name, title)>
<!ATTLIST professor id CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT courses (course+)>
<!ELEMENT course (title, credits)>
<!ATTLIST course  code CDATA #REQUIRED>
<!ELEMENT credits (#PCDATA)>

=== BENJAMINDTS/FPSuperiorDAW/1ºDAW/xml/UD.04/Universidad/universidad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE university SYSTEM "universidad.dtd">
<university>
    <department id="CS">
        <name>Computer Science</name>
        <faculty>
            <professor id="101">
                <name>Dr. Alan Turing</name>
                <title>Professor</title>
            </professor>
            <professor id="102">
                <name>Dr. Ada Lovelace</name>
                <title>Associate Professor</title>
            </professor>
        </faculty>
        <courses>
            <course code="CS101">
                <title>Introduction to Programming</title>
                <credits>3</credits>
            </course>
            <course code="CS102">
                <title>Data Structures</title>
                <credits>4</credits>
            </course>
        </courses>
    </department>
</university>
