=== BENJAMINDTS/FPSuperiorDAW/xml/UD.04/Cocina/cocina.dtd
<!ELEMENT recetario (receta+)>
<!ELEMENT receta (nombre, ingredientes)>
<!ATTLIST receta
          dificultad CDATA #REQUIRED
          porciones CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (#PCDATA)>
<!ATTLIST ingrediente
          cantidad CDATA #REQUIRED>

=== BENJAMINDTS/FPSuperiorDAW/1ºDAW/xml/UD.04/Cocina/cocina.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "cocina.dtd">
<recetario>
    <receta dificultad="fácil" porciones="2">
        <nombre>Ensalada César</nombre>
        <ingredientes>
            <ingrediente cantidad="1">Lechuga</ingrediente>
            <ingrediente cantidad="50g">Queso parmesano</ingrediente>
            <ingrediente cantidad="100g">Crutones</ingrediente>
            <ingrediente cantidad="30ml">Aderezo César</ingrediente>
        </ingredientes>
    </receta>
    <receta dificultad="media" porciones="4">
        <nombre>Pasta Carbonara</nombre>
        <ingredientes>
            <ingrediente cantidad="200g">Pasta</ingrediente>
            <ingrediente cantidad="100g">Tocino</ingrediente>
            <ingrediente cantidad="2">Huevos</ingrediente>
            <ingrediente cantidad="50g">Queso parmesano</ingrediente>
        </ingredientes>
    </receta>
</recetario>
