=== BENJAMINDTS/FPSuperiorDAW/xml/UD.04/Biblioteca/biblioteca.dtd
<!ELEMENT library (book+)>
<!ELEMENT book (title, author, publisher, year, genres+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT genres (genre+)>
<!ATTLIST book
    isbn CDATA #REQUIRED>

=== BENJAMINDTS/FPSuperiorDAW/1ºDAW/xml/UD.04/Biblioteca/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "biblioteca.dtd">
<library>
    <book isbn="978-3-16-148410-0">
        <title>Introduction to XML</title>
        <author>John Doe</author>
        <publisher>XML Publishers</publisher>
        <year>2022</year>
        <genres>
            <genre>Technology</genre>
            <genre>Education</genre>
        </genres>
    </book>
    <book isbn="978-1-23-456789-7">
        <title>Advanced XML Techniques</title>
        <author>Jane Smith</author>
        <publisher>Data Books</publisher>
        <year>2021</year>
        <genres>
            <genre>Programming</genre>
            <genre>Technology</genre>
        </genres>
    </book>
</library>
