=== BENJAMINDTS/FPSuperiorDAW/xml/UD.04/Ordenes/ordenes.dtd
<!ELEMENT ordenes (orden+)>
<!ELEMENT orden (id, cliente, productos)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT cliente (nombre, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT productos (producto+)>
<!ELEMENT producto (nombre, cantidad)>
<!ELEMENT cantidad (#PCDATA)>

=== BENJAMINDTS/FPSuperiorDAW/xml/UD.04/Ordenes/Ordenes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "ordenes.dtd">
<ordenes>
<orden>
<id>87</id>
<cliente>alfonso</cliente>
<producto>mofeta</producto>
<cliente>
<nombre>rafita</nombre>
<direccion>avpalomares</direccion>
</cliente>
<producto>
<nombre>lejia</nombre>
<cantidad>7391</cantidad>
</producto>
</orden>
</ordenes>
