=== BENJAMINDTS/FPSuperiorDAW/1ºDAW/xml/UD.04/Estudiantes/estudiantes.dtd
<!ELEMENT estudiantes (estudiante+)>
<!ELEMENT estudiante (nombre, edad, carrera)>
<!ATTLIST estudiante
          id CDATA #REQUIRED
          genero CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT carrera (#PCDATA)>

=== BENJAMINDTS/FPSuperiorDAW/1ºDAW/xml/UD.04/Estudiantes/estudiantes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "estudiantes.dtd">
<estudiantes>
    <estudiante id="001" genero="F">
        <nombre>Ana García</nombre>
        <edad>20</edad>
        <carrera>Ingeniería</carrera>
    </estudiante>
    <estudiante id="002" genero="M">
        <nombre>Juan Pérez</nombre>
        <edad>22</edad>
        <carrera>Medicina</carrera>
    </estudiante>
</estudiantes>
