=== BENJAMINDTS/FPSuperiorDAW/xml/UD.04/TiendaOnline/TiendaOnline.dtd
<!ELEMENT onlineStore (product+)>
<!ELEMENT product (name, category, price, stock)>
<!ATTLIST product
    id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price
    currency (USD) #REQUIRED>
<!ELEMENT stock (#PCDATA)>

=== BENJAMINDTS/FPSuperiorDAW/1ºDAW/xml/UD.04/TiendaOnline/TiendaOnline.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE onlineStore SYSTEM "TiendaOnline.dtd">
<onlineStore>
    <product id="001">
        <name>Wireless Mouse</name>
        <category>Electronics</category>
        <price currency="USD">25.99</price>
        <stock>150</stock>
    </product>
    <product id="002">
        <name>Gaming Keyboard</name>
        <category>Electronics</category>
        <price currency="USD">75.49</price>
        <stock>85</stock>
    </product>
</onlineStore>
